import './globals.css';

import { jacquesFrancois } from '@/app/styles/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jacquesFrancois.className}>
      <body>{children}</body>
    </html>
  );
}
